# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LZCompressor.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon, QFont

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 705)
        MainWindow.setWindowIcon(QIcon('logo0.png'))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("")
        MainWindow.setIconSize(QtCore.QSize(64, 64))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 711, 671))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(699, 13))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1, QtCore.Qt.AlignRight)
        self.tableWidget = QtWidgets.QTableWidget(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 3, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Oxygen-Icons.org-Oxygen-Actions-document-edit.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(24, 24))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.textEdit = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textEdit.setStyleSheet("")
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 1, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.checkBoxW = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxW.setGeometry(QtCore.QRect(20, 30, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.checkBoxW.setFont(font)
        self.checkBoxW.setObjectName("checkBoxW")
        self.checkBox77 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox77.setGeometry(QtCore.QRect(90, 30, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.checkBox77.setFont(font)
        self.checkBox77.setObjectName("checkBox77")
        self.checkBox78 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox78.setGeometry(QtCore.QRect(160, 20, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.checkBox78.setFont(font)
        self.checkBox78.setIconSize(QtCore.QSize(32, 32))
        self.checkBox78.setObjectName("checkBox78")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 60, 301, 181))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.dict_label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.dict_label_3.setGeometry(QtCore.QRect(10, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.dict_label_3.setFont(font)
        self.dict_label_3.setObjectName("dict_label_3")
        self.spinBox_LZW = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_LZW.setGeometry(QtCore.QRect(170, 30, 121, 31))
        self.spinBox_LZW.setMinimum(128)
        self.spinBox_LZW.setMaximum(4096)
        self.spinBox_LZW.setSingleStep(128)
        self.spinBox_LZW.setObjectName("spinBox_LZW")
        self.dict_label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.dict_label_4.setGeometry(QtCore.QRect(10, 110, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.dict_label_4.setFont(font)
        self.dict_label_4.setObjectName("dict_label_4")
        self.outEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.outEdit.setGeometry(QtCore.QRect(10, 140, 251, 31))
        self.outEdit.setObjectName("outEdit")
        self.spinBox_LZ77 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_LZ77.setGeometry(QtCore.QRect(170, 70, 121, 31))
        self.spinBox_LZ77.setMinimum(4)
        self.spinBox_LZ77.setMaximum(1024)
        self.spinBox_LZ77.setSingleStep(4)
        self.spinBox_LZ77.setProperty("value", 128)
        self.spinBox_LZ77.setObjectName("spinBox_LZ77")
        self.dict_label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.dict_label_5.setGeometry(QtCore.QRect(10, 70, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.dict_label_5.setFont(font)
        self.dict_label_5.setObjectName("dict_label_5")
        self.dirButton = QtWidgets.QPushButton(self.groupBox_3)
        self.dirButton.setGeometry(QtCore.QRect(260, 140, 31, 31))
        self.dirButton.setText("")
        self.dirButton.setIcon(icon)
        self.dirButton.setIconSize(QtCore.QSize(16, 16))
        self.dirButton.setObjectName("dirButton")
        self.compButton = QtWidgets.QPushButton(self.groupBox)
        self.compButton.setGeometry(QtCore.QRect(20, 250, 141, 31))
        self.compButton.setObjectName("compButton")
        self.decompButton = QtWidgets.QPushButton(self.groupBox)
        self.decompButton.setGeometry(QtCore.QRect(180, 250, 141, 31))
        self.decompButton.setObjectName("decompButton")
        self.infoLabel = QtWidgets.QLabel(self.groupBox)
        self.infoLabel.setGeometry(QtCore.QRect(330, 20, 351, 51))
        self.infoLabel.setStyleSheet("color:red;")
        self.infoLabel.setText("")
        self.infoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.infoLabel.setObjectName("infoLabel")
        self.comp_decomp_btn = QtWidgets.QPushButton(self.groupBox)
        self.comp_decomp_btn.setGeometry(QtCore.QRect(20, 290, 301, 31))
        self.comp_decomp_btn.setObjectName("comp_decomp_btn")
        self.listWidget = QtWidgets.QListWidget(self.groupBox)
        self.listWidget.setGeometry(QtCore.QRect(330, 130, 111, 191))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.listWidget_2 = QtWidgets.QListWidget(self.groupBox)
        self.listWidget_2.setGeometry(QtCore.QRect(450, 130, 111, 191))
        self.listWidget_2.setObjectName("listWidget_2")
        self.listWidget_3 = QtWidgets.QListWidget(self.groupBox)
        self.listWidget_3.setGeometry(QtCore.QRect(570, 130, 111, 191))
        self.listWidget_3.setObjectName("listWidget_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(370, 100, 31, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(490, 100, 41, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(610, 100, 41, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(440, 70, 141, 31))
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.groupBox, 4, 0, 1, 2)
        self.gridLayout.setRowStretch(1, 4)
        self.gridLayout.setRowStretch(3, 3)
        self.gridLayout.setRowStretch(4, 9)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(730, 10, 621, 671))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.setStretch(0, 10)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1366, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LZ Compressor"))
        self.label.setText(_translate("MainWindow", "Put the text you want to compress here or choose the file to compres/decompress:"))
        self.label_2.setText(_translate("MainWindow", "Choose the file:"))
        self.groupBox.setTitle(_translate("MainWindow", "Choose algorithms:"))
        self.checkBoxW.setText(_translate("MainWindow", "LZW"))
        self.checkBox77.setText(_translate("MainWindow", "LZ77"))
        self.checkBox78.setText(_translate("MainWindow", "LZ78"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Settings:"))
        self.dict_label_3.setText(_translate("MainWindow", "LZW Dictionary size:"))
        self.dict_label_4.setText(_translate("MainWindow", "Output file path:"))
        self.dict_label_5.setText(_translate("MainWindow", "LZ77 Buffer size:"))
        self.compButton.setText(_translate("MainWindow", "Compress"))
        self.decompButton.setText(_translate("MainWindow", "Decompress"))
        self.comp_decomp_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p>The programm will compress and decompress chosen file with all three algorithms and anylise the proccess</p></body></html>"))
        self.comp_decomp_btn.setText(_translate("MainWindow", "Analyse all"))
        self.label_4.setText(_translate("MainWindow", "LZW"))
        self.label_5.setText(_translate("MainWindow", "LZ77"))
        self.label_6.setText(_translate("MainWindow", "LZ78"))
        self.label_7.setText(_translate("MainWindow", "Compressing Steps:"))
        self.label_3.setText(_translate("MainWindow", "Graphics will be shown here"))
